services:
  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal
    restart: unless-stopped

  web:
    # Use Docker Hub image if DDALAB_USE_DOCKER_HUB=true, otherwise build locally
    image: ${DDALAB_WEB_IMAGE:-sdraeger1/ddalab-web:${VERSION:-latest}}
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    platform: linux/amd64
    env_file:
      - ./.env
    environment:
      # Next.js Environment Variables
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8001}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      NODE_ENV: production
      # Session Configuration
      SESSION_EXPIRATION: ${SESSION_EXPIRATION:-10080}
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    ports:
      - "${WEB_PORT:-3000}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - api
    networks:
      - internal
    labels:
      - "traefik.enable=true"
    restart: unless-stopped

  api:
    # Use Docker Hub image if DDALAB_API_IMAGE is set, otherwise build locally
    image: ${DDALAB_API_IMAGE:-sdraeger1/ddalab-api:${VERSION:-latest}}
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    expose:
      - "8001"
      - "8002"
    env_file:
      - ./.env
    environment:
      MINIO_HOST: "minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      DDALAB_ALLOWED_DIRS: ${DDALAB_ALLOWED_DIRS}
      PROMETHEUS_MULTIPROC_DIR: /tmp/prometheus
      DDALAB_REDIS_HOST: redis
      DDALAB_REDIS_PORT: 6379
      DDALAB_REDIS_DB: 0
      DDALAB_REDIS_PASSWORD: ${DDALAB_REDIS_PASSWORD:-}
      DDALAB_REDIS_USE_SSL: ${DDALAB_REDIS_USE_SSL:-False}
      DDALAB_PLOT_CACHE_TTL: ${DDALAB_PLOT_CACHE_TTL:-3600}
    volumes:
      - prometheus_metrics:/tmp/prometheus
      - ${DDALAB_DATA_DIR:-./data}:/app/data:rw
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - internal
    labels:
      - "traefik.enable=true"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - internal
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DDALAB_DB_USER}
      POSTGRES_PASSWORD: ${DDALAB_DB_PASSWORD}
      POSTGRES_DB: ${DDALAB_DB_NAME}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DDALAB_DB_USER}",
          "-d",
          "${DDALAB_DB_NAME}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    restart: unless-stopped

  traefik:
    image: traefik:v3.3.5
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TRAEFIK_PASSWORD_HASH=${TRAEFIK_PASSWORD_HASH}
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./certs:/etc/traefik/certs:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./traefik-logs:/traefik.log
      - type: bind
        source: ./acme.json
        target: /acme.json
    depends_on:
      postgres:
        condition: service_healthy
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"

  jaeger:
    image: jaegertracing/jaeger:2.0.0
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Legacy HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    networks:
      - internal

  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3005:3005"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - internal

volumes:
  prometheus_data:
  prometheus_metrics:
  grafana_data:
  postgres-data:
  minio-data:
  redis-data:

networks:
  internal:
    driver: bridge
