global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus scrapes itself
  - job_name: "api-metrics-server"
    static_configs:
      - targets: ["api:8002"]
