entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${TRAEFIK_ACME_EMAIL}"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: "web"

api:
  dashboard: true
  insecure: false

metrics:
  prometheus:
    entryPoint: "websecure"
    buckets: [0.1, 0.3, 1.2, 5.0]

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/server.crt"
        keyFile: "/etc/traefik/certs/server.key"

accessLog:
  filePath: "/traefik.log"
  bufferingSize: 100

http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
