# Prometheus configuration for DDALAB
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
  # External labels for this Prometheus instance
  external_labels:
    monitor: 'ddalab-monitor'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
  
  # DDALAB API metrics endpoint
  - job_name: 'ddalab-api'
    static_configs:
      - targets: ['ddalab:8002']
        labels:
          service: 'ddalab-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
    honor_labels: true

  # Redis exporter (if added)  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: 'http'

  # Traefik metrics (if enabled)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
        labels:
          service: 'traefik'

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Rule files (optional)
rule_files:
  # - 'alerts/*.yml'
  # - 'rules/*.yml'